### ISSUE TITLE
Add more CI environments

### ISSUE THREAD

**Issue by ebraminio** [behdad/harfbuzz#589]
Given recent developments of harfbuzz, the helpfulness of more CI bots is at least proved to me so I like to see the addition of more environments to harfbuzz CI.

In nutshell:
* [x] Android, as the issue on #576 (done, with much more, #592)
* [x] FreeBSD/OpenBSD/..., as #577 (done, #595)
* [x] GCC 4.x, as #585 (done, #595)
* [x] arm-none-eabi, psvita, as #451, #496, #514, http://vitasdk.org, `cmake .. -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake && make` (done, #594)

Not aware of how this particular one can be useful but after #576 I thought it would be nice if we could have Android build on our CI. With cmake this command can be accomplish that easily if ndk is installed:

`mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a ..`

but this is unable to reproduce the very issue reported on #576. Does this seem correct and does it worth to be added to our CI or we can do some autotools based ones instead? We are also not doing cmake build testing on Travis (but on Windows CI, Appveyor) as our Travis config is very autotools oriented, how about adding a third CI just for cmake and Android CI, like CircleCI?

Also a *bsd bot can be considered nice as #577, I've aggregated some solutions for it [here](https://github.com/behdad/harfbuzz/issues/577#issuecomment-338627890), is there any better one?

Also per #585, it would be nice if we could have some old GCC environment to test also.

**Comment by ebraminio** [comment]
Also a *bsd bot proved can be nice as #577, I've aggregated some solutions for it [here](https://github.com/behdad/harfbuzz/issues/577#issuecomment-338627890), is there any better one?

**Comment by ebraminio** [comment]
Also per #585, it would be nice if could have some old GCC environment to test also.

**Comment by ebraminio** [comment]
@behdad https://github.com/dockcross/dockcross which architectures do you like most?

**Comment by behdad** [comment]
> @behdad https://github.com/dockcross/dockcross which architectures do you like most?

android-arm
browser-asmjs
android-arm64
linux-mips
windows-x64

:)

**Comment by ebraminio** [comment]
@behdad, I think you meant linux-arm64? Now you should rename android-arm64 to linux-arm64 on .circleci/config.yml because of it :)

**Comment by behdad** [comment]
You are right.  Thanks. :)

**Comment by ebraminio** [comment]
PSVita part on #594

@behdad, which ubuntu version do you suggest for GCC 4.x?

**Comment by behdad** [comment]
> @behdad, which ubuntu version do you suggest for GCC 4.x?

Humm.  I don't really know those numbers.  RHEL5 might be nice if that's available.

Thanks again for all this work.  This is super helpful.

**Comment by ebraminio** [comment]
> RHEL5 might be nice if that's available.

Is ragel missing on RHEL/centos 5/7?
* https://circleci.com/gh/ebraminio/harfbuzz/111
* https://circleci.com/gh/ebraminio/harfbuzz/112

We now have GCC 4.x with FreeBSD9 but it would be nice if we have RHEL based images also.

**Comment by ebraminio** [comment]
> Thanks again for all this work. This is super helpful.

Thank you :)

**Comment by behdad** [comment]
> Is ragel missing on RHEL/centos 5/7?

Quite possibly.
